trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
  buildConfiguration: 'release'

pool:
  vmImage: 'windows-latest'

jobs:
- job: 'BuildAndPublish'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: Select dotnet core 3.1.x
    inputs:
      packageType: sdk
      version: '3.1.x'

  - task: DownloadSecureFile@1
    name: downloadAsposeLicense
    displayName: 'Download Aspose License'
    inputs:
      secureFile: AsposeTotalLicense

  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |
        $sourceDestination = "$(System.DefaultWorkingDirectory)\Pds.Contracts.ContractEventProcessor\Pds.Contracts.ContractEventProcessor.Services\DocumentServices\Resources\"

        Write-Host "Copying aspose license from $(downloadAsposeLicense.secureFilePath) to target '$sourceDestination\Aspose.Total.lic'"

        if(-not (Test-Path -Path "$sourceDestination")) {
          New-Item -Type Directory -Path "$sourceDestination"
        }

        Copy-Item -Path "$(downloadAsposeLicense.secureFilePath)" -Destination "$sourceDestination\Aspose.Total.lic"
        Write-Host "File copied!"

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: '9fd46a3f-eada-41dc-86e9-36332aeb8ef1/ecd5af68-0566-42db-8cd7-e71176254aa2'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build --collect "Code coverage" --filter TestCategory=Unit'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Website'
    inputs:
      command: publish
      publishWebProjects: false
      zipAfterPublish: true
      projects: |
        Pds.Contracts.ContractEventProcessor/Pds.Contracts.ContractEventProcessor.Func/Pds.Contracts.ContractEventProcessor.Func.csproj
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      contents: |
        azure/**
      targetFolder: '$(build.artifactstagingdirectory)/publish'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathtoPublish: '$(build.artifactstagingdirectory)/publish'
